#%RAML 1.0 DataType
type: object
properties:
  CredentialHolder:
    type: array
    items:
      properties:
        CREDENTIAL_TYPE:
          type: string
          example: "100"
          required: false
        CREDENTIAL_DESCRIPTION:
          type: string
          example: "string"
          required: false
        LICENSE_NO:
          type: string
          example: "100"
          required: false
        NAME:
          type: string
          example: "string"
          required: false
        PREVNAME1:
          type: string
          example: "string"
          required: false
        STREET:
          type: string
          example: "string"
          required: false
        CITY:
          type: string
          example: "string"
          required: false
        STATE:
          type: string
          example: "string"
          required: false
        ZIPCODE:
          type: string
          example: "100"
          required: false
        GRANTED_DATE:
          type: string
          example: "string"
          required: false
        CURRENT_THRU:
          type: string
          example: "string"
          required: false
        ELIGIBLITY_TO_PRACTICE:
          type: string
          example: "string"
          required: false
        ELIGIBILITY_COMMENTS:
          type: string
          example: "string"
          required: false
        DISCIPLINE:
          type: string
          example: "string"
          required: false
        COUNTRY:
          type: string
          example: "string"
          required: false
        CREDENTIAL_STATUS:
          type: string
          example: "string"
          required: false